name: dart_firetask
description: A sample command-line application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

homepage: https://github.com/Glitch9Inc/dart_firetask
repository: https://github.com/Glitch9Inc/dart_firetask
issue_tracker: https://github.com/Glitch9Inc/dart_firetask/issues
documentation: https://github.com/Glitch9Inc/dart_firetask#readme

version: 1.0.0
 
environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  cloud_firestore: ^5.0.1
  flutter_corelib: 
    path: ../flutter_corelib

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
